version: "3.8"

services:
  # MySQL 數據庫服務
  db:
    image: mysql:8.0
    container_name: agentai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI 後端服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agentai-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - KIMI_API_KEY=${KIMI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/backend/static/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agentai-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mysql_data:
  backend_uploads:
