version: "3.8"

services:
  # MySQL 數據庫服務
  db:
    image: mysql:8.0
    container_name: agentai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agentai_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI 後端服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agentai-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:123456@db:3306/agentai_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/backend/static/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agentai-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"
    working_dir: /app
    command:
      [
        "flutter",
        "run",
        "-d",
        "web-server",
        "--web-port=8080",
        "--web-hostname=0.0.0.0",
      ]
    volumes:
      - ./:/app

volumes:
  mysql_data:
  backend_uploads:
