// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0HPTdaB8HfNiySiCmIbn7f54W4FQi9M',
    appId: '1:41128471418:web:29316c8fde073af07004c3',
    messagingSenderId: '41128471418',
    projectId: 'agent-app-hanjisung-8ec72',
    authDomain: 'agent-app-hanjisung-8ec72.firebaseapp.com',
    storageBucket: 'agent-app-hanjisung-8ec72.firebasestorage.app',
    measurementId: 'G-KW969KQL9X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25nXwdc7BCxqdsQmtwI2XXMp-2PsNKMk',
    appId: '1:41128471418:ios:5be61f19a18f4fa57004c3',
    messagingSenderId: '41128471418',
    projectId: 'agent-app-hanjisung-8ec72',
    storageBucket: 'agent-app-hanjisung-8ec72.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_0HPTdaB8HfNiySiCmIbn7f54W4FQi9M',
    appId: '1:41128471418:web:d9700d92f6d1b6c07004c3',
    messagingSenderId: '41128471418',
    projectId: 'agent-app-hanjisung-8ec72',
    authDomain: 'agent-app-hanjisung-8ec72.firebaseapp.com',
    storageBucket: 'agent-app-hanjisung-8ec72.firebasestorage.app',
    measurementId: 'G-NDHFWK572F',
  );
}
